#ifndef NAVNET_DEFS_H
#define NAVNET_DEFS_H

#define TI_NN_SUCCESS 1
#define TI_NN_ENUM_DONE 2
#define TI_NN_NOT_SUPPORTED 6
#define TI_NN_ERR_STORAGE_FULL -1
#define TI_NN_ERR_UNKNOWN -2
#define TI_NN_ERR_VERSION -3
#define TI_NN_ERR_NOT_SUBSCRIBED -4
#define TI_NN_ERR_INVALID_SESSION -5
#define TI_NN_ERR_DATA_CORRUPTED -208
#define TI_NN_ERR_OUT_MEMORY -256
#define TI_NN_ERR_INVALID_CONNECTION -257
#define TI_NN_ERR_INCOMPLETE_TRANSACTION -258
#define TI_NN_ERR_NODE_UNRESPONSIVE -259
#define TI_NN_ERR_DATA_SIZE_EXCEEDED -261
#define TI_NN_ERR_NOT_SUPPORTED -262
#define TI_NN_ERR_INVALID_OPERATION -263
#define TI_NN_ERR_FILE_NOT_FOUND -264
#define TI_NN_ERR_ILLEGAL_ARGUMENT -265
#define TI_NN_ERR_OPERATION_CANCELLED -266
#define TI_NN_ERR_INVALID_STATE -267
#define TI_NN_ERR_INVALID_NODE_HANDLE -268
#define TI_NN_ERR_BUSY -269
#define TI_NN_ERR_INVALID_FILE -270
#define TI_NN_ERR_BATTERY -271
#define TI_NN_ERR_LOGIN -272
#define TI_NN_ERR_PROTOCOL -273
#define TI_NN_ERR_ENUM_DONE -274
#define TI_NN_ERR_DEST_FILE_NOT_FOUND -275
#define TI_NN_ERR_DEST_INVALID_FILE -276
#define TI_NN_ERR_FILE_NOT_ACCESSIBLE -277
#define TI_NN_ERR_DEST_FILE_NOT_ACCESSIBLE -278
#define TI_NN_ERR_PATH_EXISTS -279
#define TI_NN_ERR_DIR_NOT_EMPTY -280
#define TI_NN_INVALID_PORT -281
#define TI_NN_ERR_PATH_NAME_TOO_LONG -282
#define TI_NN_ERR_FOLDER_DEPTH -283
#define TI_NN_ERR_FILE_TYPE -284
#define TI_NN_ERR_ILLEGAL_CHAR_IN_NAME -285
#define TI_NN_ERR_MULTIPLE_CALL -287
#define TI_NN_ERR_MULTIPLE_CALL_DIFFERENT_PROCESS -288
#define TI_NN_ERR_MHH_DEVICE_ERROR -289
#define TI_NN_ERR_MHH_NETWORK_ERROR -290
#define TI_NN_ERR_MHH_NOT_SUPPORTED_ERROR -291

#endif